apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-tel-agent-config
  namespace: vector
data:
  vector.yaml: |
    data_dir: /vector-data-dir
    sources:
      k8s_logs_source:
        type: kubernetes_logs
        extra_field_selector: metadata.name==load-test-pod
      vector_agent_source:
        address: 0.0.0.0:9000
        type: vector
        version: "2"
    
    transforms:
      filter_k8s_logs:
        type: filter
        inputs:
          - k8s_logs_source
        condition: contains(string(.message) ?? "", "no_tag") != true
    
    sinks:
      k8s_logs_sink:
        compression: none
        encoding:
          codec: json
        inputs:
        - filter_k8s_logs
        path: /tmp/k8s-logs-%Y-%m-%d.log
        type: file
      filtered_vector_log:
        compression: none
        encoding:
          codec: json
        inputs:
        - vector_agent_source
        path: /tmp/vector-daemon-set-logs-%Y-%m-%d.log
        type: file
