apiVersion: v1
kind: Pod
metadata:
  name: load-test-pod
  namespace: demo
spec:
  containers:
    - name: load-test
      image: busybox
      command: [ "/bin/sh", "-c", "x=1; while true; do echo \"level = error, find me and fix me $x\" ;
                                  echo \"level = no_tag, i am a invisible $x\"; x=$(( $x + 1 ));  done" ]
  restartPolicy: Never