apiVersion: v1
kind: Pod
metadata:
  name: load-test-pod
  namespace: demo
spec:
  containers:
    - name: load-test
      image: hremon331046/load-tester:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: MAX_RANGE
          value: "50000"
  restartPolicy: Never