image:
  repository: timberio/vector
  pullPolicy: IfNotPresent
  tag: "nightly-2022-10-23-debian"
customConfig:
  data_dir: "/vector-data-dir"
  sources:
    file:
      type: file
      ignore_older_secs: 600
      include:
        - /tmp/demo.log
      read_from: beginning
  transforms:
    filter_error:
      type: filter
      inputs:
        - file
      condition: match(string(.message) ?? "", r'.*error.*')
    filter_info:
      type: filter
      inputs:
        - file
      condition: match(string(.message) ?? "", r'.*info.*')
    filter_debug:
      type: filter
      inputs:
        - file
      condition: match(string(.message) ?? "", r'.*debug.*')
  sinks:
    filtered_error:
      type: file
      inputs:
        - filter_error
      compression: none
      encoding:
        codec: json
      path: /tmp/vector-error-%Y-%m-%d.log
    filtered_info:
      type: file
      inputs:
        - filter_info
      compression: none
      encoding:
        codec: json
      path: /tmp/vector-info-%Y-%m-%d.log
    filtered_debug:
      type: file
      inputs:
        - filter_debug
      compression: none
      encoding:
        codec: json
      path: /tmp/vector-debug-%Y-%m-%d.log
