image:
  repository: timberio/vector
  pullPolicy: IfNotPresent
  tag: "nightly-2022-10-23-debian"
customConfig:
  data_dir: "/vector-data-dir"
  sources:
    file:
      type: file
      ignore_older_secs: 600
      include:
        - /tmp/demo.log
      read_from: beginning

    internal_log_source:
      type: internal_logs

  sinks:
    filtered_demo_log:
      type: file
      inputs:
        - file
      compression: none
      encoding:
        codec: json
      path: /tmp/vector-error-%Y-%m-%d.log

    vector_agent_sink:
      type: vector
      inputs:
        - internal_log_source
      address: http://vector-tel-agent:9000
