image:
  repository: timberio/vector
  pullPolicy: IfNotPresent
  tag: "nightly-2022-10-23-debian"
customConfig:
  data_dir: "/vector-data-dir"
  sources:
    vector_agent_source:
      type: vector
      address: 0.0.0.0:9000
      version: "2"

  sinks:
    filtered_vector_log:
      type: file
      inputs:
        - vector_agent_source
      compression: none
      encoding:
        codec: json
      path: /tmp/vector-output-%Y-%m-%d.log

