image:
  repository: timberio/vector
  pullPolicy: IfNotPresent
  tag: "nightly-2022-10-23-debian"
customConfig:
  data_dir: "/vector-data-dir"
  sources:
    file:
      type: file
      ignore_older_secs: 600
      include:
        - /tmp/demo.log
      read_from: beginning
    internal_log_source:
      type: internal_logs

  transforms:
    filter_demo_logs:
      type: filter
      inputs:
        - file
      condition: contains(string(.message) ?? "", "no_tag") != true # !match(string(.message) ?? "", r'.*no_tag.*')

  sinks:
    filtered_demo_log:
      type: file
      inputs:
        - filter_demo_logs
      compression: none
      encoding:
        codec: json
      path: /tmp/vector-demo-logs-%Y-%m-%d.log
    vector_agent_sink:
      type: vector
      inputs:
        - internal_log_source
      address: http://vector-tel-agent:9000
#    vector_log_sink:
#      type: vector
#      inputs:
#        - file
#      address: http://vector-tel-agent:9000
