apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-plane.fullname" . }}
  labels:
    {{- include "data-plane.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{.Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "data-plane.selectorLabels" . | nindent 4 }}


