apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-data-plane-config
  namespace: vector
data:
  vector.yaml: |
    data_dir: /vector-data-dir
    sources:
      k8s_logs_source:
        type: kubernetes_logs
        extra_field_selector: metadata.name==load-test-pod
      internal_log_source:
        type: internal_logs
    
    transforms:
      filter_k8s_logs:
        type: filter
        inputs:
          - k8s_logs_source
        condition: contains(string(.message) ?? "", "no_tag") != true
    
    sinks:
      k8s_logs_sink:
        compression: none
        encoding:
          codec: json
        inputs:
        - filter_k8s_logs
        path: /tmp/vector-demo-logs-%Y-%m-%d.log
        type: file
      vector_agent_sink:
        type: vector
        inputs:
          - internal_log_source
        address: http://vector-agent:9000
