apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-data-plane
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - nodes
  - configmaps
  verbs:
  - watch
  - get
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-data-plane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-data-plane
subjects:
- kind: ServiceAccount
  name: vector-data-plane
  namespace: vector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-data-plane
  namespace: vector
