apiVersion: v1
kind: Pod
metadata:
  name: load-gen-test
  namespace: demo
spec:
  containers:
    - name: load-gen
      image: hremon331046/load-gen:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: MAX_RANGE
          value: "50000"
  restartPolicy: Never